import { createWorkflowProject, type WorkflowPackage } from './project-package'

export const sampleWorkflowProject: WorkflowPackage = createWorkflowProject('Creative Intake Flow', {
  summary:
    'A reusable orchestration map that takes a campaign brief from moodboard through generation, review, and release packaging.',
  status: 'ready-for-review',
  inputs: {
    brief:
      'Build a moody synthwave launch package with stills, teaser clips, and audio atmospheres for social rollout.',
    channels: ['Instagram Reels', 'TikTok', 'YouTube Shorts'],
    sourceTools: ['Canvas Planner', 'Strudel Studio', 'Trailer Creator'],
    qualityBar: 'Everything should feel editorial, cinematic, and ready for public-facing release.',
    automationNotes: [
      'Collect references before generation begins.',
      'Shortlist only the top 3 still concepts before handing off to motion.',
      'Preserve approved prompts for reuse in future campaigns.',
    ],
  },
  scenes: [
    {
      id: 'node-1',
      template: 'collect-image',
      title: 'Gather reference frames',
      instructions: 'Pull mood references, poses, lighting examples, and typography cues.',
      outputs: ['reference board', 'palette direction'],
      x: 70,
      y: 110,
      status: 'ready',
      lane: 'image',
      notes: 'This is the intake step for every campaign.',
      tags: ['reference', 'moodboard'],
    },
    {
      id: 'node-2',
      template: 'generate-image',
      title: 'Generate key art concepts',
      instructions: 'Create still concepts for the strongest visual lanes from the board.',
      outputs: ['key art concepts', 'cover stills'],
      x: 330,
      y: 110,
      status: 'active',
      lane: 'image',
      notes: 'Use approved palette and preserve seed notes.',
      tags: ['still', 'hero'],
    },
    {
      id: 'node-3',
      template: 'generate-video',
      title: 'Build motion tests',
      instructions: 'Turn the best stills into short motion tests with camera movement.',
      outputs: ['motion tests', 'clip selects'],
      x: 600,
      y: 230,
      status: 'draft',
      lane: 'video',
      notes: 'Prioritize 6s and 12s edit formats.',
      tags: ['clip', 'timing'],
    },
    {
      id: 'node-4',
      template: 'generate-music-audio',
      title: 'Compose audio beds',
      instructions: 'Create temp score, atmospheres, and transitions to support the video cuts.',
      outputs: ['audio beds', 'transition hits'],
      x: 600,
      y: 420,
      status: 'draft',
      lane: 'audio',
      notes: 'Match energy to the reel pacing.',
      tags: ['audio', 'atmos'],
    },
    {
      id: 'node-5',
      template: 'review-select',
      title: 'Review and select',
      instructions: 'Shortlist approved stills, clips, and audio elements.',
      outputs: ['final shortlist', 'change list'],
      x: 860,
      y: 190,
      status: 'draft',
      lane: 'review',
      notes: 'Only pass forward assets that meet the editorial bar.',
      tags: ['qa', 'approval'],
    },
    {
      id: 'node-6',
      template: 'publish-export',
      title: 'Package deliverables',
      instructions: 'Prepare exports, archive prompts, and write the handoff summary.',
      outputs: ['delivery package', 'prompt archive'],
      x: 1120,
      y: 190,
      status: 'draft',
      lane: 'publish',
      notes: 'Make sure formats are ready for the publishing workflow.',
      tags: ['delivery', 'archive'],
    },
  ],
  assets: [
    {
      id: 'asset-1',
      label: 'Reference board',
      type: 'Image board',
      source: 'SyncPad / image creation',
      status: 'collected',
      notes: 'Mood references and palette cues.',
    },
    {
      id: 'asset-2',
      label: 'Logo sting audio',
      type: 'Audio effect',
      source: 'Strudel Studio',
      status: 'planned',
      notes: 'One short branded sting for the final export.',
    },
  ],
  outputs: [
    {
      id: 'output-1',
      label: 'Hero still pack',
      status: 'planned',
      target: 'Social content',
      format: 'png',
      notes: 'Approved key art in export-ready sizes.',
    },
    {
      id: 'output-2',
      label: 'Teaser clip bundle',
      status: 'planned',
      target: 'Short-form video',
      format: 'mp4',
      notes: '6s, 12s, and 15s variants.',
    },
  ],
  notes: [
    'Every workflow should show where assets come from, how they are reviewed, and what gets delivered.',
    'Use this sample as the baseline for other creative orchestration maps.',
  ],
  connections: [
    { id: 'edge-1', from: 'node-1', to: 'node-2' },
    { id: 'edge-2', from: 'node-2', to: 'node-3' },
    { id: 'edge-3', from: 'node-2', to: 'node-5' },
    { id: 'edge-4', from: 'node-3', to: 'node-5' },
    { id: 'edge-5', from: 'node-4', to: 'node-5' },
    { id: 'edge-6', from: 'node-5', to: 'node-6' },
  ],
})
